services:
  api2:
    build:
      context: .
      dockerfile: api2/Dockerfile
    container_name: api2
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=api2=debug,tower_http=debug
    networks:
      - time-service-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api1:
    build:
      context: .
      dockerfile: api1/Dockerfile
    container_name: api1
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=api1=debug,tower_http=debug
      - API2_URL=http://api2:4000
    depends_on:
      api2:
        condition: service_healthy
    networks:
      - time-service-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  time-service-network:
    driver: bridge
